// Code generated by goa v3.25.3, DO NOT EDIT.
//
// Code Generator
//
// Command:
// goa

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	_ "github.com/Sienci-Labs/gsender/machine-core/design"
	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/codegen/generator"
	"goa.design/goa/v3/eval"
	goa "goa.design/goa/v3/pkg"
)

func main() {
	var (
		out     = flag.String("output", "", "")
		version = flag.String("version", "", "")
		cmdl    = flag.String("cmd", "", "")
		debug   = flag.Bool("debug", false, "")
		ver     int
	)
	{
		flag.Parse()
		if *out == "" {
			fail("missing output flag")
		}
		if *version == "" {
			fail("missing version flag")
		}
		if *cmdl == "" {
			fail("missing cmd flag")
		}
		v, err := strconv.Atoi(*version)
		if err != nil {
			fail("invalid version %s", *version)
		}
		ver = v
	}

	startBinary := time.Now()
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Starting generated binary execution\n")
	}

	if ver > goa.Major {
		fail("cannot run goa %s on design using goa v%s\n", goa.Version(), *version)
	}

		startCheckErrors := time.Now()
		if err := eval.Context.Errors; err != nil {
			fail("%s", err.Error())
		}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Check eval.Context.Errors took %v\n", time.Since(startCheckErrors))
	}

	startRunDSL := time.Now()
	if err := eval.RunDSL(); err != nil {
		fail("%s", err.Error())
	}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] eval.RunDSL() took %v\n", time.Since(startRunDSL))
	}
	codegen.DesignVersion = ver

	startGenerate := time.Now()
	outputs, err := generator.Generate(*out, "gen", *debug)
	if err != nil {
		fail("%s", err.Error())
	}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] generator.Generate() took %v\n", time.Since(startGenerate))
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Total binary execution took %v\n", time.Since(startBinary))
	}
	fmt.Println(strings.Join(outputs, "\n"))
}

func fail(msg string, vals ...any) {
	if len(vals) == 0 {
		fmt.Fprintln(os.Stderr, msg)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, msg, vals...)
	os.Exit(1)
}
